name: Release
on:
  workflow_call:
    inputs:
      release-def-path:
        required: true
        type: string
      org:
        required: false
        type: string
        default: 'sandbox'
      loglevel:
        required: false
        type: string
        default: info
      datadog:
        required: false
        type: boolean
        default: false
      newrelic:
        required: false
        type: boolean
        default: false
    secrets:
      ENV_SFDX_AUTH_URL:
        required: true
      DEVHUB_SFDX_AUTH_URL:
        required: true
      DATADOG_HOST:
        required: false
      DATADOG_API_KEY:
        required: false
      NEWRELIC_INSIGHT_INSERT_KEYS:
        required: false
        
env:
  SFPOWERSCRIPTS_NEWRELIC: ${{ inputs.newrelic }}
  SFPOWERSCRIPTS_NEWRELIC_API_KEY: '${{ secrets.NEWRELIC_INSIGHT_INSERT_KEYS }}'
  SFPOWERSCRIPTS_DATADOG: ${{ inputs.datadog }}
  SFPOWERSCRIPTS_DATADOG_HOST: "${{ secrets.DATADOG_HOST }}"
  SFPOWERSCRIPTS_DATADOG_API_KEY: "${{ secrets.DATADOG_API_KEY }}"

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/flxbl-io/sfp:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Authenticate to devhub environment
        run: |
          echo "${{ secrets.DEVHUB_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a devhub
   
      - name: Authenticate to ${{ inputs.org }} environment
        run: |
          echo "${{ secrets.ENV_SFDX_AUTH_URL }}" > ./authfile
          sf org login sfdx-url -f authfile -a ${{ inputs.org }}

      # Authenticate to npm
      - uses: actions/setup-node@v3
        with:
         registry-url: 'https://npm.pkg.github.com'

      # Release to environment
      - name: 'Release to ${{ inputs.org }}'
        run: 'sfp release -u ${{ inputs.org }} -v devhub -p ${{ inputs.release-def-path }} --npm --scope ${{ github.repository_owner }} --generatechangelog --branchname changelog -g "::group::,::endgroup::" --loglevel ${{ inputs.loglevel }}'
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  